### ISSUE TITLE
Any idea when this will be released?

### ISSUE THREAD

**Issue by gregoks** [stryker-mutator/azure-devops-mutationreport-publisher#5]
hi guys,

Do you know if this extension will be released any time soon? 
What is the status? am I able to use it to see if it works or this is very preliminary version?

Thanks,

Greg

**Comment by Mobrockers** [comment]
I have very little experience with web development and documentation for azure devops web extensions is sparse /non existent so progress is slow and motivation is low. There is no working demo yet, but I do hope to work on this more when Microsoft releases enough documentation to get this to a working state.

**Comment by Mobrockers** [comment]
Those samples are unfortunately quite old. Microsoft is not updating the libraries used there any longer. There are new samples but they moved to react and webpack with completely new api's and no documentation so that's quite a change for me.

**Comment by Mobrockers** [comment]
@gregoks sooooon :D
