### ISSUE TITLE
Switch to Node10 Execution Handler

### ISSUE THREAD

**Issue by pinkfloydx33** [stryker-mutator/azure-devops-mutationreport-publisher#600]
Azure DevOps is beginning the process to deprecate the `Node` execution handler in favor of `Node10`. As of a few days ago, custom tasks across the board **spam warnings** into build pipelines, the mutation publishing task being one of them.

See here for more info:
https://aka.ms/migrateTaskNode10

**Comment by rouke-broersma** [comment]
Good to know, thanks!
