### ISSUE TITLE
Default report name to the name it picks up

### ISSUE THREAD

**Issue by defunky** [stryker-mutator/azure-devops-mutationreport-publisher#730]
At the moment it seems to default display report names to `mutation-report-(x).html`. It should use the same report name that it was originally generated as (e.g. name assigned in the stryker-config.json)

**Comment by rouke-broersma** [comment]
This is a good suggestion. We actually already display the name correctly in the UI but we don't store the report with the correct name. This should be fixed here: https://github.com/stryker-mutator/azure-devops-mutationreport-publisher/blob/4b3a93e6c5aaf675a9b25f81f06a49d0a2a76c24/extension/PublishMutationReport/src/publish.ts#L19**
